# Generated by Django 4.2.16 on 2024-12-20 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_organization_team_vehicle_vehicleentryregistry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehiclePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("quantity", models.IntegerField()),
                ("unit_value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="api.vehicleentryregistry",
                    ),
                ),
            ],
        ),
    ]
