# Generated by Django 4.2.16 on 2024-12-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_vehiclepart"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleentryregistry",
            name="status",
            field=models.CharField(
                choices=[
                    ("Aprovado", "Approved"),
                    ("Aguardando aprovação", "Waiting Approval"),
                ],
                default="APPROVED",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
