# Generated by Django 4.2.16 on 2025-01-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_vehicleentryregistry_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleentryregistry",
            name="observation",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
