# Generated by Django 4.2.16 on 2025-01-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_vehicleentryregistry_observation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleentryregistry",
            name="status",
            field=models.CharField(
                choices=[
                    ("Aprovado", "Approved"),
                    ("Não aprovado", "Not Approved"),
                    ("Aguardando aprovação", "Waiting Approval"),
                ],
                max_length=20,
            ),
        ),
    ]
