# Generated by Django 4.2.16 on 2025-02-22 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_team_organization_workshop_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleentryregistry",
            name="assessment_responsible",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle_entries",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
