# Generated by Django 4.2.16 on 2025-02-23 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_vehicleentryregistry_assessment_responsible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicleentryregistry",
            name="assessment_responsible",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
