# Generated by Django 4.2.16 on 2025-03-30 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_vehicleentryregistry_assessment_responsible"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicleentryregistry",
            old_name="responsable_team",
            new_name="responsible_team",
        ),
    ]
